services:
  - type: web
    name: vnsports
    runtime: node
    plan: free
    region: singapore
    rootDir: vnsports
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
